### ISSUE TITLE
Needs to be fixed

### ISSUE THREAD

**Issue by tagshch** [Barakex/Epam_sber_test_create_react_app#1]
Put all redux files (app actions, sagas, etc) to separate folder
(it can be named "redux"). Same goes to css.

Remove not used files (e.g. tests).

Move footer and header components from containers.
They aren't connected to redux, so they are just simple/dumb components.

Use forEach() instead of map()
https://github.com/Barakex/EpamTest/blob/8fb34cf3ae67f77c990d2750271f7ee2cc2227b6/src/sagas.js#L31

Divide types to separate file
https://github.com/Barakex/EpamTest/blob/8fb34cf3ae67f77c990d2750271f7ee2cc2227b6/src/actions.js#L1

Use arrow functions
https://github.com/Barakex/EpamTest/blob/8fb34cf3ae67f77c990d2750271f7ee2cc2227b6/src/actions.js#L9

Simplify
https://github.com/Barakex/EpamTest/blob/8fb34cf3ae67f77c990d2750271f7ee2cc2227b6/src/containers/Dashboard/Search/index.js#L38

```
<Modal hendleClick={() => this.closeWindow()} text="Результатов не найдено"/>
<Modal handleClick={this.closeWindow} text="Результатов не найдено"/>
```

Grammar errors in naming
https://github.com/Barakex/EpamTest/blob/8fb34cf3ae67f77c990d2750271f7ee2cc2227b6/src/reducers/data.js#L3
https://github.com/Barakex/EpamTest/blob/8fb34cf3ae67f77c990d2750271f7ee2cc2227b6/src/reducers/episodes.js#L3

**Comment by Barakex** [comment]
Fixed in еру commit - "feature/fixStructure"
